### ISSUE TITLE
could you please share the paper with us?

### ISSUE THREAD

**Issue by saladcat** [xiaxin1998/DHCN#1]
there is only code but no paper. it's hard to understand the cod.

**Comment by Coder-Yu** [comment]
The paper will be online available soon (2-3 days, depends on the arXiv review process).

**Comment by saladcat** [comment]
> The paper will be online available soon (2-3 days, depends on the arXiv review process).

get, thanks

**Comment by Coder-Yu** [comment]
It is available now. Take a look at the homepage for the shared dropbox link.

**Comment by saladcat** [comment]
> It is available now. Take a look at the homepage for the shared dropbox link.

great! thanks~
