### ISSUE TITLE
i want to sue the sample dataset

### ISSUE THREAD

**Issue by zhangguozheng-1** [xiaxin1998/DHCN#13]
i want to test my model in the sample dataset(Mentioned in your code)，I didn’t find it in the dataset link, where can I get it, or the sample is generated according to certain rules. 
It would be appreciated if you could provide it!!

**Comment by xiaxin1998** [comment]
You can find sample dataset here: https://github.com/CRIPAC-DIG/SR-GNN/tree/master/datasets.
But this dataset is created by randomly selecting from the origin dataset and is used just for debugging codes. It is very small.

**Comment by zhangguozheng-1** [comment]
i got it, Thank you so much for sharing !
