### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.  Process finished with exit code 1

### ISSUE THREAD

**Issue by shuqincao** [xiaxin1998/DHCN#14]
model.py的第40行“ item_embeddings = np.sum(final, 0) / (self.layers+1)” 报错：
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Process finished with exit code 1

**Comment by Coder-Yu** [comment]
please refer to https://github.com/xiaxin1998/DHCN/issues/9#issue-998871253
