### ISSUE TITLE
Garbled datasets

### ISSUE THREAD

**Issue by EnterUName** [xiaxin1998/DHCN#15]
The datasets downloaded from link "https://www.dropbox.com/sh/j12um64gsig5wqk/AAD4Vov6hUGwbLoVxh3wASg_a?dl=0"
are garbled.I tired to solve this problem by changing the encoding format and other ways,but it still goes wrong.Could you please send me a dataset?My email address is 1045102854@qq.com.I will be appreciated for your reply, thank you very much! 

从您给的链接中下载下来的数据集一直是乱码的格式。我尝试修改编码格式和其他方法都无法获得正确的数据集。可以给我发送一份新的数据集文件嘛？我的邮箱地址是1045102854@qq.com。非常感谢，期待您的回复

**Comment by Coder-Yu** [comment]
> Datasets are available at Dropbox: https://www.dropbox.com/sh/j12um64gsig5wqk/AAD4Vov6hUGwbLoVxh3wASg_a?dl=0 **_The datasets are already preprocessed and encoded by pickle._**

Have you seen this in the readme file

**Comment by EnterUName** [comment]
My fault!Forget this.
