### ISSUE TITLE
The

### ISSUE THREAD

**Issue by ZeroerWiser** [xiaxin1998/DHCN#16]

**Comment by ZeroerWiser** [comment]
I have tried serveral dataset, but all raise the error of "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (825304,) + inhomogeneous part.", the code "self.raw = np.asarray(data[0])" raised this error.

**Comment by xiaxin1998** [comment]
Please just nake sure you have use the same environment in Readme.

**Comment by onetance** [comment]
Hello, I also met the same problem, may I ask you to solve it?

**Comment by onetance** [comment]
Hello, I have the same problem and I don't know how to solve it. Have you solved it yet?
