### ISSUE TITLE
It seems that your model is not compared with GCE-GNN.

### ISSUE THREAD

**Issue by Fenglixia** [xiaxin1998/DHCN#5]
The result of the baseline methods is to reference GCE-GNN. It seems that your model is not compared with GCE-GNN.

**Comment by Coder-Yu** [comment]
When we submitted this paper to AAAI, we did not notice GCE-GNN. After the paper got accepted, we followed the reviews and reconducted part of the experiments. We then found this paper and referred to the results presented in GCE-GNN for convenience. On Tmall, the best performance of our model is presented in the ablation study. By removing attention and position embeddings, our model beats GCE-GNN by a large margin. On Nowplaying, our model achieves larger precision values, while the MRR values are still lower than that of GCE-GNN. On Diginetica, GCE-GNN shows better performance. Overall, the performance of our model is on par with that of GCE-GNN. We will compare our upgraded model with GCE-GNN in our journal extension. Thanks for your suggestion.
