### ISSUE TITLE
Do you have any RuntimeError when you run this code?

### ISSUE THREAD

**Issue by git-x5** [xiaxin1998/DHCN#8]
In file "model.py" ,line 51, in forward 
     item_embeddings = np.sum(final, 0)

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

**Comment by xiaxin1998** [comment]
Hi I do not have this error when running. But I think it is because of version.
Please try to change line 50 as 'item_embeddings = np.sum(final.detach().numpy(), 0)' 
or change line 49 as 'final.append(item_embeddings.detach().numpy())'.

**Comment by xiaxin1998** [comment]
Hi I do not encounter this error, but I think it is because of version.
Now I have changed line 50 and 51, please try to see whether the codes can be run successfully in your environment.
